/**:
  ros__parameters:

    image_transport: raw

    family: "36h11"

    size: 0.5

    max_hamming: 0

    pose_estimation_method: "pnp"

    publish_tf: true

    detector:
      threads: 2
      decimate: 0.5
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: true

    tag:
      ids: [0]
      frames: ["tag36h11:0"]
      sizes: [0.5]
